### ISSUE TITLE
Pagespeed insights/ Core vitals issue

### ISSUE THREAD

**Issue by LiverpoolOwen** [andrezimpel/gatsby-plugin-gdpr-cookies#40]
Great work on the plugin,  I use it on all my sites.

I am working on my page speed due to the upcoming changes in google algorythm and I have run into a problem.  
"Remove unused JavaScript to reduce bytes consumed by network activity. "
I guess we don't really need to load this script until the user has consented right?

![image](https://user-images.githubusercontent.com/4280944/110969060-28cbcf80-8350-11eb-8df2-89c08f56c035.png)

**Comment by andrezimpel** [comment]
hey @LiverpoolOwen Thank you for the kind words! I will (finally) finish up v2 of the plugin. This issue will be resolved because gtag.js will not be included during ssr. Actually none of the tracking scripts will be included in the static html. You can have a look at the v2 branch - I still gotta do some cleanup tho.

**Comment by LiverpoolOwen** [comment]
Sure I will take a look mate.  if there is anything I can help with let me know.

**Comment by andrezimpel** [comment]
Testing v2 would help a lot!

**Comment by LiverpoolOwen** [comment]
sure, il have a play around with it on my site

**Comment by andrezimpel** [comment]
@LiverpoolOwen any feedback yet?
